### ISSUE TITLE
Can't create pod lib

### ISSUE THREAD

**Issue by ReDetection** [CocoaPods/pod-template#95]
Failing after asking for class prefix. Not sure if it's a template's issue, but since this is called from template, I've filed an issue here. Can you please fix it?

```
2015-03-06 08:32:12.679 ruby[92768:1202695] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 33. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.22.0/lib/xcodeproj/plist_helper.rb:176:in `RubyHashPropertyListRead': Unable to read plist data: 8?X}? (IOError)
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.22.0/lib/xcodeproj/plist_helper.rb:61:in `read'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.22.0/lib/xcodeproj/plist_helper.rb:6:in `read_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.22.0/lib/xcodeproj/project.rb:191:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.22.0/lib/xcodeproj/project.rb:92:in `open'
	from /Users/sbuglakov/src/self/RACSignal+ReDetection/setup/ProjectManipulator.rb:29:in `run'
	from /Users/sbuglakov/src/self/RACSignal+ReDetection/setup/ConfigureiOS.rb:73:in `perform'
	from /Users/sbuglakov/src/self/RACSignal+ReDetection/setup/ConfigureiOS.rb:7:in `perform'
	from /Users/sbuglakov/src/self/RACSignal+ReDetection/setup/TemplateConfigurator.rb:72:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```

**Comment by orta** [comment]
This might have been because of a space in the title, I've made sure the latest release with #105  deal with spaces correctly.

**Comment by ReDetection** [comment]
@orta no, I had no spaces in title, it was the plus sign (because I wanted to made a lib of categories)

**Comment by orta** [comment]
Yeah, I think that should be fixed by the same solution, will just give it a test run now

**Comment by orta** [comment]
Nope. Re-opening.

**Comment by fulldecent** [comment]
@ReDetection Could you please confirm this is still broken and provide a test case?

**Comment by ReDetection** [comment]
@fulldecent as of version 0.39.0, which is the latests stable one, this is still an issue. Steps to reproduce is to try to create any lib with plus sign in it, eg `pod lib create NSString+UsefulExtension` and fill a few fields on request. 
Feel free to create an exact test case

**Comment by fulldecent** [comment]
I have reported this issue upstream to

https://github.com/CocoaPods/Xcodeproj/issues/369

Please close here.

**Comment by segiddins** [comment]
👍 we'll track this is Xcodeproj to fix, thanks for the issue @ReDetection !
